Properly report test suite results without error.
This fixes errors such as:

~~~
/usr/share/gems/gems/shindo-0.3.9/lib/shindo/bin.rb:83:in `<top (required)>': undefined method `join' for "[red]1 failed[/],, [red]1 errored[/], and [green]662 succeeded[/]in [bold]11.777175132830932[/] seconds":String (NoMethodError)
	from /usr/share/gems/gems/shindo-0.3.9/bin/shindo:5:in `require_relative'
	from /usr/share/gems/gems/shindo-0.3.9/bin/shindo:5:in `<top (required)>'
	from /usr/bin/shindo:23:in `load'
	from /usr/bin/shindo:23:in `<main>'
~~~

The line adding fancy `,` and `and` was not never exercised until the
status was not extended by `errored` field in b56710f. This brings it to
life and improves the formatting from:

~~~
1 failed, 1 errored, 3 pending, 955 succeeded in 15.626122789453369 seconds
~~~

to

~~~
1 failed, 1 errored, 3 pending and 955 succeeded in 15.758976896940673 seconds
~~~

The other option would be to just the delete the line.